version: '3'
services:
  redis:
    container_name: redis
    image: redis:7.0.5
    networks:
      - redis-dist
    ports:
      - "6379:6379"
  spring-dist-lock-1:
    container_name: spring-dist-lock-1
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8081:8080"
  spring-dist-lock-2:
    container_name: spring-dist-lock-2
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8082:8080"
  spring-dist-lock-3:
    container_name: spring-dist-lock-3
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8083:8080"
  spring-dist-lock-4:
    container_name: spring-dist-lock-4
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8084:8080"
  spring-dist-lock-5:
    container_name: spring-dist-lock-5
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8085:8080"
  spring-dist-lock-6:
    container_name: spring-dist-lock-6
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8086:8080"
  spring-dist-lock-7:
    container_name: spring-dist-lock-7
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8087:8080"
  spring-dist-lock-8:
    container_name: spring-dist-lock-8
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8088:8080"
  spring-dist-lock-9:
    container_name: spring-dist-lock-9
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8089:8080"
  spring-dist-lock-10:
    container_name: spring-dist-lock-10
    build: .
    image: spring-dist-lock
    networks:
      - redis-dist
    depends_on:
      - redis
    ports:
      - "8090:8080"

networks:
  redis-dist:
    driver: bridge